/**
 * Explore Three Cities — Curated Place Data
 * London • Portsmouth • Gosport
 * 
 * All coordinates are WGS84 decimal degrees.
 * Hours and prices are approximate — check official sites for latest info.
 */

window.App = window.App || {};

App.CITIES = {
  london: {
    id: 'london',
    name: 'London',
    tagline: 'Explore the Capital',
    emoji: '🇬🇧',
    description: '38 incredible places to discover',
    heroGradient: 'linear-gradient(135deg, #1a1a2e 0%, #e53935 50%, #ff6f00 100%)',
  },
  portsmouth: {
    id: 'portsmouth',
    name: 'Portsmouth',
    tagline: 'Maritime Heritage City',
    emoji: '⚓',
    description: '18 amazing waterfront experiences',
    heroGradient: 'linear-gradient(135deg, #0d1b2a 0%, #1565c0 50%, #42a5f5 100%)',
  },
  gosport: {
    id: 'gosport',
    name: 'Gosport',
    tagline: 'Hidden Coastal Gem',
    emoji: '🚢',
    description: '15 unique discoveries await',
    heroGradient: 'linear-gradient(135deg, #0a1f1a 0%, #00897b 50%, #4db6ac 100%)',
  },
};

App.CITY_ORDER = ['london', 'portsmouth', 'gosport'];

App.CATEGORIES = [
  { id: 'all',      name: 'All Places',    emoji: '✨' },
  { id: 'sights',   name: 'Sights',        emoji: '🏛️' },
  { id: 'museums',  name: 'Museums',       emoji: '🎨' },
  { id: 'shopping', name: 'Shopping',      emoji: '🛍️' },
  { id: 'parks',    name: 'Parks',         emoji: '🌳' },
  { id: 'food',     name: 'Food & Markets', emoji: '🍽️' },
  { id: 'family',   name: 'Family Fun',    emoji: '🎪' },
  { id: 'wizard',   name: 'Harry Potter',  emoji: '⚡' },
  { id: 'gems',     name: 'Hidden Gems',   emoji: '💎' },
];

App.CATEGORY_GRADIENTS = {
  sights:   'linear-gradient(135deg, #ff6b35 0%, #f7c948 100%)',
  museums:  'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  shopping: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
  parks:    'linear-gradient(135deg, #11998e 0%, #38ef7d 100%)',
  food:     'linear-gradient(135deg, #ee0979 0%, #ff6a00 100%)',
  family:   'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  wizard:   'linear-gradient(135deg, #1a1a2e 0%, #4a0e8f 40%, #e6b800 100%)',
  gems:     'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
};

App.PLACES = [

  /* ═══════════════════════════════════════
     LONDON — 38 Places
     ═══════════════════════════════════════ */

  {
    id: 'london-big-ben',
    city: 'london',
    name: 'Big Ben & Parliament',
    category: 'sights',
    emoji: '🕰️',
    description: 'Iconic clock tower and Gothic Revival parliament building on the Thames. The most photographed landmark in London.',
    hours: 'Exterior: 24/7 · Tours: Mon–Sat 9:00–17:00',
    price: 'Free (exterior) · £28 (tour)',
    lat: 51.5007,
    lng: -0.1245,
  },
  {
    id: 'london-buckingham',
    city: 'london',
    name: 'Buckingham Palace',
    category: 'sights',
    emoji: '👑',
    description: 'Official residence of the British monarch. The Changing of the Guard ceremony is a must-see spectacle.',
    hours: 'State Rooms: Jul–Sep 9:30–19:30',
    price: '~£30 (State Rooms)',
    lat: 51.5014,
    lng: -0.1419,
  },
  {
    id: 'london-tower',
    city: 'london',
    name: 'Tower of London',
    category: 'museums',
    emoji: '🏰',
    description: '1,000-year-old castle housing the Crown Jewels. A UNESCO World Heritage Site with Yeoman Warder tours.',
    hours: 'Tue–Sat 9:00–17:30 · Sun–Mon 10:00–17:30',
    price: '~£33',
    lat: 51.5081,
    lng: -0.0761,
  },
  {
    id: 'london-eye',
    city: 'london',
    name: 'London Eye',
    category: 'sights',
    emoji: '🎡',
    description: '135m observation wheel on the South Bank offering 360° panoramic views across the city. A rotation takes ~30 minutes.',
    hours: 'Daily 10:00–18:00 (later in summer)',
    price: '~£32',
    lat: 51.5033,
    lng: -0.1197,
  },
  {
    id: 'london-british-museum',
    city: 'london',
    name: 'British Museum',
    category: 'museums',
    emoji: '🏛️',
    description: 'World-class free museum with 8 million works spanning human history, including the Rosetta Stone and Parthenon sculptures.',
    hours: 'Daily 10:00–17:00 · Fri until 20:30',
    price: 'Free',
    lat: 51.5194,
    lng: -0.1270,
  },
  {
    id: 'london-natural-history',
    city: 'london',
    name: 'Natural History Museum',
    category: 'family',
    emoji: '🦕',
    description: 'Stunning Romanesque building housing dinosaur skeletons, a life-size blue whale, and interactive Earth galleries. Perfect for families.',
    hours: 'Daily 10:00–17:50',
    price: 'Free',
    lat: 51.4967,
    lng: -0.1764,
  },
  {
    id: 'london-hyde-park',
    city: 'london',
    name: 'Hyde Park',
    category: 'parks',
    emoji: '🌿',
    description: 'One of London\'s Royal Parks covering 350 acres. Features the Serpentine lake, Diana Memorial Fountain, and Speaker\'s Corner.',
    hours: 'Daily 5:00–00:00',
    price: 'Free',
    lat: 51.5073,
    lng: -0.1657,
  },
  {
    id: 'london-camden-market',
    city: 'london',
    name: 'Camden Market',
    category: 'shopping',
    emoji: '🎸',
    description: 'Eclectic market district with 1,000+ stalls selling street food, vintage clothes, crafts, and art alongside the Regent\'s Canal.',
    hours: 'Daily 10:00–18:00',
    price: 'Free entry',
    lat: 51.5414,
    lng: -0.1467,
  },
  {
    id: 'london-borough-market',
    city: 'london',
    name: 'Borough Market',
    category: 'food',
    emoji: '🧀',
    description: 'London\'s oldest food market (1,000+ years). Artisan producers selling gourmet cheese, fresh produce, baked goods, and global street food.',
    hours: 'Tue–Fri 10:00–17:00 · Sat 9:00–17:00',
    price: 'Free entry',
    lat: 51.5055,
    lng: -0.0910,
  },
  {
    id: 'london-science-museum',
    city: 'london',
    name: 'Science Museum',
    category: 'family',
    emoji: '🔬',
    description: 'Free interactive museum covering space exploration, computing history, and engineering. The Wonderlab gallery is great for kids.',
    hours: 'Daily 10:00–18:00',
    price: 'Free (special exhibitions paid)',
    lat: 51.4978,
    lng: -0.1745,
  },

  /* ─── More London Landmarks ─────────── */

  {
    id: 'london-the-shard',
    city: 'london',
    name: 'The Shard',
    category: 'sights',
    emoji: '🔷',
    description: 'Western Europe\'s tallest building at 310m. The View from The Shard offers breathtaking 360° panoramas across 40 miles of London.',
    hours: 'Daily 10:00–22:00',
    price: '~£32',
    lat: 51.5045,
    lng: -0.0865,
  },
  {
    id: 'london-westminster-abbey',
    city: 'london',
    name: 'Westminster Abbey',
    category: 'sights',
    emoji: '⛪',
    description: 'Gothic masterpiece where monarchs have been crowned since 1066. Final resting place of kings, queens, poets, and scientists.',
    hours: 'Mon–Sat 9:30–15:30 · Closed Sun for worship',
    price: '~£27',
    lat: 51.4993,
    lng: -0.1273,
  },
  {
    id: 'london-covent-garden',
    city: 'london',
    name: 'Covent Garden',
    category: 'shopping',
    emoji: '🎭',
    description: 'Vibrant piazza with street performers, boutique shops, restaurants, and the Royal Opera House. A buzzing atmosphere day and night.',
    hours: 'Daily 10:00–20:00 (shops vary)',
    price: 'Free entry',
    lat: 51.5117,
    lng: -0.1240,
  },
  {
    id: 'london-tate-modern',
    city: 'london',
    name: 'Tate Modern',
    category: 'museums',
    emoji: '🎨',
    description: 'World-renowned modern art gallery in a converted power station on the South Bank. Free permanent collection includes Picasso, Warhol, and Dalí.',
    hours: 'Sun–Thu 10:00–18:00 · Fri–Sat 10:00–22:00',
    price: 'Free (special exhibitions paid)',
    lat: 51.5076,
    lng: -0.0994,
  },

  /* ─── London Parks & Green Spaces ──── */

  {
    id: 'london-regents-park',
    city: 'london',
    name: 'Regent\'s Park',
    category: 'parks',
    emoji: '🌹',
    description: 'Elegant Royal Park with Queen Mary\'s Rose Garden (12,000 roses), an open-air theatre, boating lake, and London Zoo at its northern edge.',
    hours: 'Daily 5:00–21:30 (varies seasonally)',
    price: 'Free',
    lat: 51.5273,
    lng: -0.1536,
  },
  {
    id: 'london-st-james-park',
    city: 'london',
    name: 'St James\'s Park',
    category: 'parks',
    emoji: '🦢',
    description: 'The oldest Royal Park with stunning views of Buckingham Palace across the lake. Famous for its resident pelicans fed daily at 14:30.',
    hours: 'Daily 5:00–00:00',
    price: 'Free',
    lat: 51.5025,
    lng: -0.1340,
  },
  {
    id: 'london-greenwich-park',
    city: 'london',
    name: 'Greenwich Park',
    category: 'parks',
    emoji: '🔭',
    description: 'UNESCO World Heritage Site with the Royal Observatory, the Prime Meridian Line, and spectacular panoramic views of Canary Wharf and the Thames.',
    hours: 'Daily 6:00–18:00 (winter) · 6:00–21:00 (summer)',
    price: 'Free (Observatory ~£18)',
    lat: 51.4769,
    lng: -0.0005,
  },
  {
    id: 'london-kew-gardens',
    city: 'london',
    name: 'Kew Gardens',
    category: 'parks',
    emoji: '🌺',
    description: 'UNESCO-listed Royal Botanic Gardens with 50,000+ living plants, the iconic Palm House glasshouse, a treetop walkway, and seasonal flower displays.',
    hours: 'Daily 10:00–18:00 (summer) · 10:00–16:00 (winter)',
    price: '~£19',
    lat: 51.4787,
    lng: -0.2956,
  },
  {
    id: 'london-richmond-park',
    city: 'london',
    name: 'Richmond Park',
    category: 'parks',
    emoji: '🦌',
    description: 'London\'s largest Royal Park (2,500 acres) with 600 free-roaming red and fallow deer. Perfect for cycling, walking, and spotting wildlife.',
    hours: 'Daily 7:00–dusk (seasonal)',
    price: 'Free',
    lat: 51.4430,
    lng: -0.2744,
  },
  {
    id: 'london-hampstead-heath',
    city: 'london',
    name: 'Hampstead Heath',
    category: 'parks',
    emoji: '🌄',
    description: 'Wild ancient heathland with swimming ponds, woodland trails, and Parliament Hill — one of the best panoramic viewpoints across the entire London skyline.',
    hours: 'Open 24/7',
    price: 'Free',
    lat: 51.5613,
    lng: -0.1640,
  },

  /* ─── Harry Potter Locations ───────── */

  {
    id: 'london-platform-934',
    city: 'london',
    name: 'Platform 9¾',
    category: 'wizard',
    emoji: '⚡',
    description: 'The iconic trolley-through-the-wall photo spot at King\'s Cross Station. Adjacent Harry Potter Shop sells official merchandise.',
    hours: 'Daily 8:00–22:00 (shop) · Photo spot 24/7',
    price: 'Free (photos) · Shop varies',
    lat: 51.5322,
    lng: -0.1240,
  },
  {
    id: 'london-wb-studio-tour',
    city: 'london',
    name: 'Warner Bros. Studio Tour',
    category: 'wizard',
    emoji: '🧙',
    description: 'The Making of Harry Potter — walk through the Great Hall, Diagon Alley, Dumbledore\'s office, and ride a broomstick. Book tickets in advance!',
    hours: 'Daily 9:00–22:00 (timed entry)',
    price: '~£53 (must pre-book)',
    lat: 51.6903,
    lng: -0.4181,
  },
  {
    id: 'london-leadenhall-market',
    city: 'london',
    name: 'Leadenhall Market',
    category: 'wizard',
    emoji: '🐉',
    description: 'Stunning Victorian covered market used as the entrance to Diagon Alley and the Leaky Cauldron in the Philosopher\'s Stone film.',
    hours: 'Mon–Fri 10:00–18:00 · Sat limited · Sun closed',
    price: 'Free entry',
    lat: 51.5129,
    lng: -0.0832,
  },
  {
    id: 'london-millennium-bridge',
    city: 'london',
    name: 'Millennium Bridge',
    category: 'wizard',
    emoji: '🌉',
    description: 'The elegant pedestrian bridge dramatically destroyed by Death Eaters in the Half-Blood Prince film. Stunning views of St Paul\'s and the Tate.',
    hours: 'Open 24/7',
    price: 'Free',
    lat: 51.5095,
    lng: -0.0985,
  },
  {
    id: 'london-palace-theatre',
    city: 'london',
    name: 'Palace Theatre — Cursed Child',
    category: 'wizard',
    emoji: '🎭',
    description: 'Home of "Harry Potter and the Cursed Child" — the award-winning stage play continuing Harry\'s story. A magical theatrical experience.',
    hours: 'Show times vary · Box office 10:00–20:00',
    price: 'From ~£30',
    lat: 51.5133,
    lng: -0.1312,
  },
  {
    id: 'london-zoo-reptile-house',
    city: 'london',
    name: 'London Zoo — Reptile House',
    category: 'wizard',
    emoji: '🐍',
    description: 'Where Harry first spoke Parseltongue to a boa constrictor in the Philosopher\'s Stone. The real reptile house is in ZSL London Zoo, Regent\'s Park.',
    hours: 'Daily 10:00–17:00 (Mar–Oct) · 10:00–16:00 (Nov–Feb)',
    price: '~£27 (zoo entry)',
    lat: 51.5353,
    lng: -0.1534,
  },

  /* ─── Leicester Square ─────────────── */

  {
    id: 'london-leicester-square',
    city: 'london',
    name: 'Leicester Square',
    category: 'sights',
    emoji: '🌟',
    description: 'London\'s glittering entertainment hub surrounded by cinemas, theatres, and restaurants. Home to major film premieres including every Harry Potter premiere.',
    hours: 'Open 24/7',
    price: 'Free',
    lat: 51.5103,
    lng: -0.1301,
  },

  /* ─── Best Eats in London ──────────── */

  {
    id: 'london-brick-lane',
    city: 'london',
    name: 'Brick Lane',
    category: 'food',
    emoji: '🍛',
    description: 'Famous "Curry Mile" in the heart of East London. Dozens of Bengali and Indian restaurants, plus vintage shops, street art, and a buzzing Sunday market.',
    hours: 'Restaurants: Daily 11:00–23:00 · Market: Sun 10:00–17:00',
    price: 'Mains from ~£8',
    lat: 51.5215,
    lng: -0.0715,
  },
  {
    id: 'london-chinatown',
    city: 'london',
    name: 'Chinatown',
    category: 'food',
    emoji: '🥟',
    description: 'Vibrant district around Gerrard Street packed with authentic Chinese, Taiwanese, Japanese, and Vietnamese restaurants. Try the dim sum and bubble tea.',
    hours: 'Daily 11:00–23:00 (varies by restaurant)',
    price: 'Mains from ~£10',
    lat: 51.5113,
    lng: -0.1312,
  },
  {
    id: 'london-maltby-street',
    city: 'london',
    name: 'Maltby Street Market',
    category: 'food',
    emoji: '🥩',
    description: 'Hidden artisan food market under Victorian railway arches in Bermondsey. Gourmet street food, craft beer, and specialist producers — a local favourite.',
    hours: 'Sat 10:00–17:00 · Sun 11:00–16:00',
    price: 'Free entry · Street food from ~£6',
    lat: 51.4985,
    lng: -0.0760,
  },
  {
    id: 'london-seven-dials',
    city: 'london',
    name: 'Seven Dials Market',
    category: 'food',
    emoji: '🌮',
    description: 'Trendy indoor food hall near Covent Garden with 15+ street food vendors, a Cheese Bar, and a gin cocktail bar in a beautiful converted warehouse.',
    hours: 'Mon–Sat 10:00–22:00 · Sun 12:00–21:00',
    price: 'Dishes from ~£7',
    lat: 51.5138,
    lng: -0.1267,
  },
  {
    id: 'london-flat-iron-square',
    city: 'london',
    name: 'Flat Iron Square',
    category: 'food',
    emoji: '🍕',
    description: 'Buzzing open-air food court near Borough Market with global street food, craft beer bars, live music, and a relaxed community vibe. Great for dinner.',
    hours: 'Mon–Wed 8:00–23:00 · Thu–Sat 8:00–00:00 · Sun 10:00–22:00',
    price: 'Dishes from ~£7',
    lat: 51.5027,
    lng: -0.0974,
  },
  {
    id: 'london-spitalfields',
    city: 'london',
    name: 'Old Spitalfields Market',
    category: 'food',
    emoji: '🧁',
    description: 'Historic East London market (est. 1638) with excellent street food, artisan crafts, vintage fashion, and antiques. Busiest on Thursdays and weekends.',
    hours: 'Daily 10:00–20:00 · Restaurants until 23:00',
    price: 'Free entry · Food from ~£6',
    lat: 51.5196,
    lng: -0.0756,
  },

  /* ─── More Harry Potter Locations ──── */

  {
    id: 'london-minalima',
    city: 'london',
    name: 'House of MinaLima',
    category: 'wizard',
    emoji: '📜',
    description: 'Free gallery in Soho by the graphic designers behind all the Harry Potter films. See original props: the Marauder\'s Map, Daily Prophet, Hogwarts letters, and more.',
    hours: 'Daily 10:00–19:00',
    price: 'Free',
    lat: 51.5134,
    lng: -0.1365,
  },
  {
    id: 'london-australia-house',
    city: 'london',
    name: 'Australia House — Gringotts',
    category: 'wizard',
    emoji: '🏦',
    description: 'The stunning Edwardian building on the Strand used as the interior of Gringotts Wizarding Bank. The ornate banking hall is unmistakable.',
    hours: 'Exterior: 24/7 · Interior: not open to public',
    price: 'Free (exterior only)',
    lat: 51.5131,
    lng: -0.1163,
  },
  {
    id: 'london-claremont-square',
    city: 'london',
    name: 'Claremont Square — Grimmauld Place',
    category: 'wizard',
    emoji: '🏚️',
    description: 'This elegant Georgian square in Islington was used as the exterior of 12 Grimmauld Place — the Black family home and Order of the Phoenix headquarters.',
    hours: 'Open 24/7 (public square)',
    price: 'Free',
    lat: 51.5296,
    lng: -0.1099,
  },
  {
    id: 'london-st-pancras',
    city: 'london',
    name: 'St Pancras Station',
    category: 'wizard',
    emoji: '🚂',
    description: 'The stunning Gothic Revival façade was used as the exterior of King\'s Cross Station in the films. Harry and Ron fly the Ford Anglia from here in Chamber of Secrets.',
    hours: 'Open 24/7',
    price: 'Free',
    lat: 51.5321,
    lng: -0.1262,
  },
  {
    id: 'london-cecil-court',
    city: 'london',
    name: 'Cecil Court — Real Diagon Alley',
    category: 'wizard',
    emoji: '📚',
    description: 'Charming pedestrian alley of antiquarian bookshops near Leicester Square. Said to be J.K. Rowling\'s inspiration for Diagon Alley — it truly feels magical.',
    hours: 'Mon–Sat 10:00–18:00 · Sun limited',
    price: 'Free',
    lat: 51.5105,
    lng: -0.1275,
  },

  /* ═══════════════════════════════════════
     PORTSMOUTH — 14 Places
     ═══════════════════════════════════════ */

  {
    id: 'portsmouth-historic-dockyard',
    city: 'portsmouth',
    name: 'Historic Dockyard',
    category: 'museums',
    emoji: '⚓',
    description: 'Home to HMS Victory, the Mary Rose Museum, and HMS Warrior 1860. Britain\'s premier naval heritage site.',
    hours: 'Daily 10:00–17:30 (Apr–Oct) · 10:00–17:00 (Nov–Mar)',
    price: '~£23–£40 (full ticket)',
    lat: 50.8005,
    lng: -1.1095,
  },
  {
    id: 'portsmouth-spinnaker',
    city: 'portsmouth',
    name: 'Spinnaker Tower',
    category: 'sights',
    emoji: '🗼',
    description: '170m iconic sail-shaped observation tower with three viewing decks and a glass floor. Panoramic Solent views.',
    hours: 'Daily 10:00–18:00',
    price: '~£15',
    lat: 50.7956,
    lng: -1.1086,
  },
  {
    id: 'portsmouth-gunwharf',
    city: 'portsmouth',
    name: 'Gunwharf Quays',
    category: 'shopping',
    emoji: '🛍️',
    description: 'Waterfront designer outlet shopping complex with 90+ brands, restaurants, cinema, and bowling.',
    hours: 'Mon–Fri 10:00–20:00 · Sat 9:00–20:00 · Sun 10:00–17:00',
    price: 'Free entry',
    lat: 50.7949,
    lng: -1.1058,
  },
  {
    id: 'portsmouth-dday',
    city: 'portsmouth',
    name: 'The D-Day Story',
    category: 'museums',
    emoji: '🎖️',
    description: 'The only UK museum dedicated to the D-Day landings, housing the original Overlord Embroidery.',
    hours: 'Daily 10:00–17:30 (Apr–Sep) · 10:00–17:00 (Oct–Mar)',
    price: '~£12',
    lat: 50.7798,
    lng: -1.0893,
  },
  {
    id: 'portsmouth-southsea-castle',
    city: 'portsmouth',
    name: 'Southsea Castle',
    category: 'gems',
    emoji: '🏰',
    description: 'Tudor-era fort built by Henry VIII in 1544. Free museum with exhibits on Portsmouth\'s coastal defences.',
    hours: 'Apr–Oct: Tue–Sun 10:00–17:00',
    price: 'Free',
    lat: 50.7778,
    lng: -1.0903,
  },
  {
    id: 'portsmouth-aquarium',
    city: 'portsmouth',
    name: 'Blue Reef Aquarium',
    category: 'family',
    emoji: '🐠',
    description: 'Compact aquarium on Southsea seafront featuring a coral reef, sharks, seahorses, and an underwater tunnel.',
    hours: 'Daily 10:00–17:00',
    price: '~£12',
    lat: 50.7788,
    lng: -1.0879,
  },
  {
    id: 'portsmouth-southsea-common',
    city: 'portsmouth',
    name: 'Southsea Common',
    category: 'parks',
    emoji: '🌊',
    description: 'Large seafront common with gardens, memorials, and play areas. Hosts major events and offers views to the Isle of Wight.',
    hours: 'Open 24/7',
    price: 'Free',
    lat: 50.7839,
    lng: -1.0920,
  },
  {
    id: 'portsmouth-old-town',
    city: 'portsmouth',
    name: 'Old Portsmouth',
    category: 'gems',
    emoji: '🧭',
    description: 'Charming cobbled streets, the Round & Square Towers, and stunning harbour views from the Hot Walls.',
    hours: 'Open 24/7 (outdoor area)',
    price: 'Free',
    lat: 50.7900,
    lng: -1.1050,
  },
  {
    id: 'portsmouth-victoria-park',
    city: 'portsmouth',
    name: 'Victoria Park',
    category: 'parks',
    emoji: '🦢',
    description: 'Pretty Victorian park near the commercial centre with a lake, aviaries, and seasonal flowerbeds.',
    hours: 'Dawn to dusk',
    price: 'Free',
    lat: 50.7988,
    lng: -1.0924,
  },
  {
    id: 'portsmouth-cathedral',
    city: 'portsmouth',
    name: 'Portsmouth Cathedral',
    category: 'gems',
    emoji: '⛪',
    description: 'Beautiful Anglican cathedral dating from 1180, blending medieval, Georgian, and 20th-century architecture.',
    hours: 'Daily 7:30–18:00',
    price: 'Free',
    lat: 50.7896,
    lng: -1.1048,
  },

  /* ─── Portsmouth Shopping ───────────── */

  {
    id: 'portsmouth-commercial-road',
    city: 'portsmouth',
    name: 'Commercial Road',
    category: 'shopping',
    emoji: '🏬',
    description: 'Portsmouth\'s main high street with Primark, TK Maxx, H&M, and the Cascades Shopping Centre. The city\'s busiest retail strip.',
    hours: 'Mon–Sat 9:00–17:30 · Sun 10:30–16:30',
    price: 'Free entry',
    lat: 50.7985,
    lng: -1.0918,
  },
  {
    id: 'portsmouth-palmerston-road',
    city: 'portsmouth',
    name: 'Palmerston Road, Southsea',
    category: 'shopping',
    emoji: '☕',
    description: 'Southsea\'s charming shopping street lined with independent boutiques, coffee shops, delis, and gift stores. A relaxed alternative to the high street.',
    hours: 'Mon–Sat 9:00–17:30 · Sun 10:00–16:00',
    price: 'Free entry',
    lat: 50.7866,
    lng: -1.0870,
  },
  {
    id: 'portsmouth-albert-road',
    city: 'portsmouth',
    name: 'Albert Road, Southsea',
    category: 'shopping',
    emoji: '🎵',
    description: 'Bohemian street packed with vintage shops, record stores, tattoo parlours, independent bars, and quirky cafés. The creative heart of Southsea.',
    hours: 'Daily · Hours vary by shop',
    price: 'Free entry',
    lat: 50.7879,
    lng: -1.0815,
  },
  {
    id: 'portsmouth-port-solent',
    city: 'portsmouth',
    name: 'Port Solent',
    category: 'shopping',
    emoji: '⛵',
    description: 'Waterfront leisure village with shops, restaurants, a Vue cinema, and a marina. Great for an evening out with harbour views.',
    hours: 'Daily 10:00–22:00 (shops close earlier)',
    price: 'Free entry · Free parking',
    lat: 50.8423,
    lng: -1.1039,
  },

  /* ─── Portsmouth Food & Drink ───────── */

  {
    id: 'portsmouth-pie-vinyl',
    city: 'portsmouth',
    name: 'Pie & Vinyl',
    category: 'food',
    emoji: '🍰',
    description: 'Beloved Southsea café on Castle Road combining gourmet pies, homemade cakes, and a vinyl record shop. Try the steak & ale pie — a local legend.',
    hours: 'Tue–Sat 10:00–17:00 · Sun 11:00–16:00 · Mon closed',
    price: 'Pies from ~£6',
    lat: 50.7889,
    lng: -1.0861,
  },
  {
    id: 'portsmouth-still-west',
    city: 'portsmouth',
    name: 'The Still & West',
    category: 'food',
    emoji: '🍻',
    description: 'Historic waterfront pub at Bath Square in Old Portsmouth. Enjoy fish & chips, seafood, and real ales with spectacular harbour views from the terrace.',
    hours: 'Mon–Sat 11:00–23:00 · Sun 12:00–22:30',
    price: 'Mains from ~£12',
    lat: 50.7900,
    lng: -1.1068,
  },
  {
    id: 'portsmouth-seafront-dining',
    city: 'portsmouth',
    name: 'Southsea Seafront Dining',
    category: 'food',
    emoji: '🌞',
    description: 'String of beachfront cafés, ice cream parlours, and fish & chip shops along the Southsea seafront. Classic British seaside dining with Isle of Wight views.',
    hours: 'Daily 9:00–21:00 (seasonal)',
    price: 'Fish & chips from ~£8',
    lat: 50.7810,
    lng: -1.0860,
  },
  {
    id: 'portsmouth-clarence-pier',
    city: 'portsmouth',
    name: 'Clarence Pier',
    category: 'food',
    emoji: '🍭',
    description: 'Seaside amusement pier with classic fish & chips, doughnuts, candy floss, and arcade games. A fun, nostalgic British seaside experience for all ages.',
    hours: 'Daily 10:00–21:00 (seasonal hours)',
    price: 'Food from ~£5',
    lat: 50.7830,
    lng: -1.0972,
  },

  /* ═══════════════════════════════════════
     GOSPORT — 15 Places
     ═══════════════════════════════════════ */

  {
    id: 'gosport-explosion',
    city: 'gosport',
    name: 'Explosion Museum',
    category: 'museums',
    emoji: '💥',
    description: 'Housed in the 18th-century Priddy\'s Hard armaments depot. Traces the history of naval weaponry from gunpowder to guided missiles.',
    hours: 'Apr–Oct: Daily 10:00–17:00 · Nov–Mar: Weekends 10:00–16:00',
    price: '~£10',
    lat: 50.8075,
    lng: -1.1264,
  },
  {
    id: 'gosport-submarine',
    city: 'gosport',
    name: 'Submarine Museum',
    category: 'museums',
    emoji: '🔱',
    description: 'Home to HMS Alliance (WWII submarine) and Holland 1 (Britain\'s first submarine). Walk through a real submarine.',
    hours: 'Daily 10:00–17:00 (Apr–Oct) · 10:00–16:00 (Nov–Mar)',
    price: '~£16',
    lat: 50.7875,
    lng: -1.1200,
  },
  {
    id: 'gosport-stokes-bay',
    city: 'gosport',
    name: 'Stokes Bay',
    category: 'parks',
    emoji: '🏖️',
    description: 'Popular shingle beach with panoramic Isle of Wight views, a sailing club, seasonal café, and No.2 Battery Fort ruins.',
    hours: 'Open 24/7',
    price: 'Free',
    lat: 50.7786,
    lng: -1.1500,
  },
  {
    id: 'gosport-haslar-marina',
    city: 'gosport',
    name: 'Haslar Marina',
    category: 'gems',
    emoji: '⛵',
    description: 'One of the south coast\'s largest marinas. Walk along the harbour wall with views across to Portsmouth and Navy ships.',
    hours: 'Open 24/7 (public walkway)',
    price: 'Free',
    lat: 50.7917,
    lng: -1.1189,
  },
  {
    id: 'gosport-high-street',
    city: 'gosport',
    name: 'Falkland Gardens',
    category: 'gems',
    emoji: '🌺',
    description: 'Pleasant pedestrianised high street leading to Falkland Gardens with ferry terminal views and a memorial garden.',
    hours: 'Open 24/7 · Shops: ~9:00–17:30',
    price: 'Free',
    lat: 50.7955,
    lng: -1.1175,
  },
  {
    id: 'gosport-lee-on-solent',
    city: 'gosport',
    name: 'Lee-on-the-Solent',
    category: 'parks',
    emoji: '🌅',
    description: 'Expansive shingle beach with a long promenade, free splash park, children\'s play area, cafés, and watersports.',
    hours: 'Open 24/7',
    price: 'Free',
    lat: 50.8030,
    lng: -1.2011,
  },
  {
    id: 'gosport-alver-valley',
    city: 'gosport',
    name: 'Alver Valley Country Park',
    category: 'parks',
    emoji: '🦋',
    description: '580-acre green space with woodlands, meadows, wetlands, cycling trails, and a "Wild Play" area for kids.',
    hours: 'Dawn to dusk',
    price: 'Free',
    lat: 50.7971,
    lng: -1.1692,
  },
  {
    id: 'gosport-holy-trinity',
    city: 'gosport',
    name: 'Holy Trinity Church',
    category: 'gems',
    emoji: '🕊️',
    description: 'Beautiful Georgian church (1696) at Trinity Green, one of Gosport\'s oldest buildings with historic naval connections.',
    hours: 'Services & open days',
    price: 'Free',
    lat: 50.7931,
    lng: -1.1205,
  },
  {
    id: 'gosport-ferry',
    city: 'gosport',
    name: 'Gosport Ferry',
    category: 'gems',
    emoji: '⛴️',
    description: 'The iconic harbour ferry crossing from Gosport to Portsmouth (2 mins). Stunning waterfront views and a quintessential local experience.',
    hours: 'Mon–Sat 5:30–00:00 · Sun 6:30–00:00',
    price: '~£3.80 return',
    lat: 50.7960,
    lng: -1.1170,
  },

  /* ─── Gosport Shopping ─────────────── */

  {
    id: 'gosport-stoke-road',
    city: 'gosport',
    name: 'Stoke Road',
    category: 'shopping',
    emoji: '🛒',
    description: 'Gosport\'s traditional local shopping street with independent stores, charity shops with hidden treasures, bakeries, and everyday essentials.',
    hours: 'Mon–Sat 9:00–17:30 · Sun limited',
    price: 'Free entry',
    lat: 50.7926,
    lng: -1.1312,
  },
  {
    id: 'gosport-market',
    city: 'gosport',
    name: 'Gosport Tuesday Market',
    category: 'shopping',
    emoji: '🧺',
    description: 'Popular weekly street market in the High Street with fresh fruit & veg, clothing, household goods, flowers, and local produce. A Gosport tradition.',
    hours: 'Tuesdays 8:30–15:00',
    price: 'Free entry',
    lat: 50.7950,
    lng: -1.1178,
  },
  {
    id: 'gosport-alverstoke-village',
    city: 'gosport',
    name: 'Alverstoke Village',
    category: 'shopping',
    emoji: '🏡',
    description: 'Picturesque village centre with a lovely deli, gift shops, a traditional pub, and a community feel. Perfect stop before or after Stokes Bay.',
    hours: 'Mon–Sat 9:00–17:00 · Sun limited',
    price: 'Free entry',
    lat: 50.7868,
    lng: -1.1385,
  },

  /* ─── Gosport Food & Drink ─────────── */

  {
    id: 'gosport-stokes-bay-cafe',
    city: 'gosport',
    name: 'Stokes Bay Café',
    category: 'food',
    emoji: '☕',
    description: 'Seasonal beachfront café right on the shingle at Stokes Bay. Hot drinks, bacon rolls, and ice cream with panoramic Isle of Wight views.',
    hours: 'Daily 9:00–17:00 (seasonal · weather dependent)',
    price: 'Snacks from ~£3',
    lat: 50.7790,
    lng: -1.1490,
  },
  {
    id: 'gosport-alverbank',
    city: 'gosport',
    name: 'The Alverbank Country House',
    category: 'food',
    emoji: '🌿',
    description: 'Charming country house hotel in Alverstoke with a well-regarded restaurant and beautiful gardens. Afternoon tea, Sunday roasts, and seasonal British menus.',
    hours: 'Daily 12:00–14:30 · 18:00–21:00',
    price: 'Mains from ~£14 · Afternoon tea ~£20',
    lat: 50.7875,
    lng: -1.1370,
  },
  {
    id: 'gosport-waterfront-pubs',
    city: 'gosport',
    name: 'Gosport Waterfront Pubs',
    category: 'food',
    emoji: '🍺',
    description: 'Cluster of welcoming pubs near the ferry terminal and harbour. Enjoy real ales, pub grub, and views of Portsmouth Harbour and passing Navy ships.',
    hours: 'Daily 11:00–23:00',
    price: 'Mains from ~£10',
    lat: 50.7952,
    lng: -1.1180,
  },
];
